### ISSUE TITLE
1.2.4版本服务器盔甲失效以及物品拾起时崩溃

### ISSUE THREAD

**Issue by 6371peter** [yuoft/Endless#4]
Endless-1.16.5-1.2.4
Forge:36.2.35

服务器中身穿全套无尽护甲仍会受到伤害（包括摔落，攻击受伤等）,用的forge-1.16.5-36.2.35,仅装了本模组，并且服务器中拾起或用指令清理（kill @e[type=item]）任何可以快速拾起的物品的（无尽护甲或者寰宇支配之剑等）都会导致服务器崩溃，单人游戏正常。

**Comment by 6371peter** [comment]
崩溃报告

Time: 2022/5/25 上午8:48
Description: Ticking entity

java.lang.NoSuchMethodError: com.yuo.endless.Items.Tool.EndlessItemEntity.func_174872_o()I
	at com.yuo.endless.Items.Tool.EndlessItemEntity.func_70106_y(EndlessItemEntity.java:46) ~[endless:1.16.5-1.2.4] {re:classloading}
	at net.minecraft.entity.item.ItemEntity.func_70071_h_(ItemEntity.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.yuo.endless.Items.Tool.EndlessItemEntity.func_70106_y(EndlessItemEntity.java:46) ~[endless:1.16.5-1.2.4] {re:classloading}
	at net.minecraft.entity.item.ItemEntity.func_70071_h_(ItemEntity.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:item (com.yuo.endless.Items.Tool.EndlessItemEntity)
	Entity ID: 480
	Entity Name: Air
	Entity's Exact location: -294.68, 68.00, 107.30
	Entity's Block location: World: (-295,68,107), Chunk: (at 9,4,11 in -19,6; contains blocks -304,0,96 to -289,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.00, -0.08, -0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['6371peter'/272, l='ServerLevel[world]', x=-294.65, y=68.00, z=107.30]]
	Chunk stats: ServerChunkCache: 2422
	Level dimension: minecraft:overworld
	Level spawn location: World: (-176,78,112), Chunk: (at 0,4,0 in -11,7; contains blocks -176,0,112 to -161,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1114 game time, 1114 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 105817 (now: false), thunder time: 148305 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.15, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 716057088 bytes (682 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xmx2048M -Xms2048M -XX:+UnlockExperimentalVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.35-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Endless-1.16.5-1.2.4.jar                          |Endless                       |endless                       |1.16.5-1.2.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 094196aa-538a-4281-b491-fb8973e37cee
	Player Count: 1 / 20; [ServerPlayerEntity['6371peter'/272, l='ServerLevel[world]', x=-294.65, y=68.00, z=107.30]]
	Data Packs: vanilla, mod:forge, mod:endless
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by zfms4188** [comment]
确实 我也发现了 我使用的是混合端 也会出现上面的问题 另外 使用漏斗吸取 也会出现这个问题

**Comment by yuoft** [comment]
你试试换成34版本forge，看看是不是还会崩溃

**Comment by zfms4188** [comment]
> 

有眉目了吗

**Comment by yuoft** [comment]
> > 
> 
> 有眉目了吗

已经修复了，本地服务器测试没问题。稍后会发布新版本
